# Generated by Django 5.0.2 on 2024-03-07 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('men', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ник'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='men.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='men.perfume', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='review',
            name='product_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='men.perfume'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfume',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='men.tags', verbose_name='Теги'),
        ),
    ]
